### ISSUE TITLE
cron_prev loops forever when asked for "* * * 1 2 *", today is the 1st of November

### ISSUE THREAD

**Issue by nicodato** [exander77/supertinycron#3] opened 2023-11-01 17:49 UTC
Today, 2023-11-01, I noticed that cron_prev() looped forever when asked for `* * * 1 2 *` (1st of February).
It also fails with `* * * 2 2 *` and `* * * 3 2 *`, but not with `* * * 4 2 *`.
I'm on Linux, with glibc.

I debugged ccronexpr.c and I think I found the issue, so I made a PR #2 

Looks like `cron_mktime` was receiving as input the date 30th of February. So, it returned 2nd of March.
I think somehow the algorithm was trying to reach February but `cron_mktime` was preventing that from happening.

**Comment by exander77** [comment] 2023-11-04 02:36
Hmm, that's interesting, I don't think I touched this logic when doing a tonne changes, so this maybe an issue from the original code.

Have you noticed any issues with cron_next?

**Comment by exander77** [comment] 2023-11-04 02:58
I pulled your change and added some tests. Doesn't seem to break any existing tests.

**Comment by nicodato** [comment] 2023-11-04 03:04
> Hmm, that's interesting, I don't think I touched this logic when doing a tonne changes, so this maybe an issue from the original code.

This bug comes from the original code. I was using ccronexpr and encounter this issue. I tried to upgrade ccronexpr, but I found out ccronexpr was inactive and redirecting to your repo. So tried yours and the bug was still there.

> Have you noticed any issues with cron_next?

`cron_next` was working fine with that cron expression. I think that is because `cron_next` uses `reset_min` instead of `reset_max`.

There is something odd, I'm almost 100% sure that the `* * * 2 2 *` cron expression was being used before the 1st of November. So I think that suddenly, when the month changed, that cron expression crashed. I don't understand why.

This is used in a system that something was to run for some time. Like "every 2nd of February run for 5 hours". So the system uses `cron_prev` and see if `now` is inside the interval that something has to run.

> I unified both cron_prev and cron_next code, so it is easier to maintain, but cron_prev has very limited number of tests.
> 
> So you expect something like this, I assume?
> 
> ```c
>     check_fn(cron_prev, "* * * 1 2 *", "2023-11-01_00:00:00", "2023-02-01_23:59:59", __LINE__);
>     check_fn(cron_prev, "* * * 2 2 *", "2023-11-01_00:00:00", "2023-02-02_23:59:59", __LINE__);
>     check_fn(cron_prev, "* * * 3 2 *", "2023-11-01_00:00:00", "2023-02-03_23:59:59", __LINE__);
>     check_fn(cron_prev, "* * * 4 2 *", "2023-11-01_00:00:00", "2023-02-04_23:59:59", __LINE__);
> ```

I think so. The exact cron expression that generated the issue was `0 56 17 2 2 *`, and I was expecting `2023-02-02 17:56:00` (I use `CRON_USE_LOCAL_TIME`)

> I pulled your change and added some tests. Doesn't seem to break any existing tests.

Thank you! Could you reproduce the issue? I don't have musl, so I thought that maybe `mktime` doesn't  change to March and instead it sets 28th of February.

**Comment by exander77** [comment] 2023-11-04 03:44
I think this was broken by one of the previous fixes in `cron_prev`, `cron_prev` was kinda hackishly added in the past. There were several issues over the years with it and several pull requests.

I unified 95% of the code with `cron_next`, but there are some slight differences. I think this one is caused by applying max resets and then applying field. This was changed for `cron_prev` in the past due to a different error. So it may have workder, but failed for a different case.

And if you set a day and then month then you get what you described above:
> Looks like cron_mktime was receiving as input the date 30th of February. So, it returned 2nd of March.

I think this may be ultimately fixed by having different reset order for `cron_prev` and `cron_next`, swapping `cron_prev` resets for a month and day of month. But this doesn't seem to break anything on a first glance.

**Comment by exander77** [comment] 2023-11-04 03:47
Btw, you can compile statically with musl-gcc even if you are using glibc.
The issue is the same on musl. So at least this is consistent.

**Comment by exander77** [comment] 2023-11-04 11:03
@nicodato Btw, if you use `cron_prev` intensively, you may create some tests for it in `ccronexpr_test.c` like shown above. It will make less probable any feature will be broken in the future.

There are currently 235 `cron_next` tests, but only 14 `cron_prev` tests including 4 new I did last night. I made at least 100 new tests, when I added new features recently. It was a pain, but makes it much easier to spot an error when there is a good coverage.

**Comment by nicodato** [comment] 2023-11-05 03:24
> @nicodato Btw, if you use `cron_prev` intensively, you may create some tests for it in `ccronexpr_test.c` like shown above. It will make less probable any feature will be broken in the future.

Good idea! I'll see what I can add, and I'll send de PR

**Comment by nicodato** [comment] 2023-11-06 15:36
Ready, see #4

**Comment by exander77** [comment] 2023-11-14 01:58
> Ready, see #4

Merged everything, great job!

**Closed** 2023-11-26 22:03 UTC
